version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
